HW3
se-barabash/homework pull request #2
Opened 2024-11-18 01:40 UTC by se-barabash

2024-11-19 20:05 UTC, myroslav-kolomiiets requested changes

2024-11-19 20:05 UTC, myroslav-kolomiiets commented on HW3.html
> +         iterativeOddSumTo(11)
В завданні перевірка написана так не випадково:
```
console.log(iterativeOddSumTo(1)) // 1
console.log(iterativeOddSumTo(10)) // 25
```
Будь ласка, не міняйте це самостійно

І якщо запустити ваш код з такою перевіркою, то результат буде
```
1
undefined
25
undefined
```

Проблема у вас на 33 рядку, подумайте чому такий результат та як отримати правильний:
```
1
25
```

2024-11-20 00:33 UTC, se-barabash commented on HW3.html
> +         iterativeOddSumTo(11)
![ітерація](https://github.com/user-attachments/assets/4fbe3221-1674-41c7-ab65-7b95fcc18769)

не розумію, про що мова йде: які undefined? надсилаю знімку для наочности; я дійсно не розумію)))

2024-11-22 18:41 UTC, myroslav-kolomiiets approved these changes
Зараз вірно

2024-11-24 16:02 UTC, merged